name: impostor_futbol
description: Juego tipo impostor adaptado a fútbol (Jugador / Club / Balón de Oro)
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter  # Añadido para permitir pruebas con flutter_test

flutter:
  uses-material-design: true
